//! `gm-ca` × `gmssl` CLI TLCP interop tests.
//!
//! Validates that X.509 certificates issued by
//! [`gm_ca::cert::CaSigner`] round-trip through `gmssl tlcp_server` /
//! `gmssl tlcp_client` CLI binaries (GmSSL 3.1.1+). This is the
//! reverse direction from `gm-tlcp/tests/gmssl_interop.rs` — there
//! the certs are generated by `gmssl certgen` and the connector
//! uses them; here the certs are generated by gm-ca's CA signer
//! API and the **server side is GmSSL CLI**.
//!
//! ## Mode A (this file)
//!
//! - **Server** = `gmssl tlcp_server` (GmSSL-signed server cert).
//! - **Client** = `gm_tlcp::tlcp::TlcpConnector` configured with
//!   **gm-ca-signed** client cert chain (`[client_sign, client_enc,
//!   root_ca]`) where the root CA is the same self-signed SM2 cert
//!   gm-ca emits. GmSSL's `-cacert` is set to the gm-ca root so
//!   `tls_recv_client_certificate` accepts the chain.
//!
//! Proves: gm-ca's wire-format X.509 + SM2 SPKI/sigAlg + chain
//! construction is accepted by GmSSL 2026-06+ master during the
//! client-cert verification path that closes the ECC suites.
//!
//! ## Why #[ignore]
//!
//! Both tests are `#[ignore = "requires the gmssl binary on PATH"]`
//! to match the convention in `gm-tlcp/tests/gmssl_interop.rs`. Run
//! locally with:
//!
//! ```bash
//! cargo test -p gm-ca --features tlcp-profiles --test gmssl_cli_interop \
//!     -- --ignored --nocapture
//! ```
//!
//! CI gating is the responsibility of a separate
//! `gm-ca × GmSSL TLCP Interop` workflow (Phase 11b) which builds the
//! `docker/Dockerfile.gmssl` image and exposes `gmssl` on PATH via
//! the wrapper script the gm-tlcp CI job already uses.

#![cfg(feature = "tlcp-profiles")]
#![cfg(test)]

use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use gm_ca::cert::CaSigner;
use gm_ca::cert_profile::CertProfile;
use gm_crypto::sm2::Sm2KeyPair;
use gm_crypto::x509::CsrBuilder;
use gm_tlcp::tlcp::TlcpConnector;
use tokio::io::AsyncReadExt;
use tokio::net::TcpStream;
use tokio::process::Child;

// ---------------------------------------------------------------------------
// Cipher suite IDs (GB/T 38636-2020 §6.4.5.2.1 表 2)
// ---------------------------------------------------------------------------

/// `TLS_ECDHE_ECDSA_SM4_GCM_SM3` — ECDHE + SM2 sign + SM4-GCM + SM3.
const ECDHE_ECDSA_SM4_GCM_SM3: [u8; 2] = [0xE0, 0x51];
/// `TLS_ECC_SM4_GCM_SM3` — static ECDH + SM2 sign + SM4-GCM + SM3.
const ECC_SM4_GCM_SM3: [u8; 2] = [0xE0, 0x53];

const TLCP_CIPHER_SUITES: &[[u8; 2]] = &[ECDHE_ECDSA_SM4_GCM_SM3, ECC_SM4_GCM_SM3];

/// GmSSL master `gmssl certgen` / `gmssl tlcp_server` use the standard
/// GM/T 0003 distid `1234567812345678`. Match the gm-crypto default.
const GMSSL_DEFAULT_DISTID: &str = "1234567812345678";

// ---------------------------------------------------------------------------
// Cert hierarchy generated by gm-ca
// ---------------------------------------------------------------------------

/// GmSSL-facing paths and pre-decoded DER/PEM buffers for a cert
/// hierarchy issued entirely by [`gm_ca::cert::CaSigner`].
///
/// Layout (matches GmSSL's `tlcp_server` expectations):
///
/// ```text
/// ca.key / ca.crt                       self-signed SM2 root CA
///   │
///   ├── signs ─► server_sign.crt        server signing cert (KU: digitalSignature)
///   └── signs ─► server_enc.crt         server encryption cert (KU: keyAgreement)
/// chain.crt  = server_sign.crt ‖ server_enc.crt   (concatenated PEM, fed to -cert)
/// combined.key = server_sign.key ‖ server_enc.key  (SEC1 unencrypted PEMs,
///                                                   concatenated, fed to -key)
///
///   ├── signs ─► client_sign.crt        client signing cert (KU: digitalSignature)
///   └── signs ─► client_enc.crt         client encryption cert (KU: keyAgreement + keyEncipherment)
/// ```
#[derive(Debug)]
struct GmcaCerts {
    /// Self-signed root CA PEM (path for GmSSL `-cacert`).
    ca_cert: PathBuf,
    /// Concatenated server chain PEM (path for GmSSL `-cert`).
    server_chain: PathBuf,
    /// Concatenated server private-key PEM (path for GmSSL `-key`,
    /// SEC1 unencrypted concatenated).
    server_combined_key: PathBuf,
    /// DER-encoded server signing cert (for chain introspection / debug).
    #[allow(dead_code)]
    server_sign_cert_der: Vec<u8>,
    /// DER-encoded server encryption cert.
    #[allow(dead_code)]
    server_enc_cert_der: Vec<u8>,
    /// DER-encoded client signing cert.
    client_sign_cert_der: Vec<u8>,
    /// DER-encoded client encryption cert.
    client_enc_cert_der: Vec<u8>,
    /// DER-encoded root CA cert.
    ca_cert_der: Vec<u8>,
    /// Client signing key SEC1 unencrypted PEM (gm-tlcp connector input).
    client_sign_key_pem: String,
    /// Client encryption key SEC1 unencrypted PEM (gm-tlcp connector input).
    client_enc_key_pem: String,
    /// 65-byte SEC1 uncompressed SM2 pubkey extracted from server
    /// signing cert (gm-tlcp connector `with_server_sign_key` input).
    server_sign_pub_65: Vec<u8>,
}

/// Generate the cert hierarchy above under `out_dir`. Every cert is
/// signed by the same root CA via [`CaSigner`].
fn generate_gmca_test_certs(out_dir: &Path) -> Result<GmcaCerts, String> {
    std::fs::create_dir_all(out_dir).map_err(|e| format!("mkdir {}: {}", out_dir.display(), e))?;

    // ---- Root CA (self-signed SM2) ----
    let ca_key = Sm2KeyPair::generate().map_err(|e| format!("CA keygen: {}", e))?;
    let ca_signer = CaSigner::new(ca_key, "GM ECC Test CA (gm-ca interop)");
    let ca_pem = ca_signer
        .self_sign_ca(365, &CertProfile::root_ca())
        .map_err(|e| format!("CA self_sign_ca: {}", e))?;
    let ca_cert_der = pem::parse(ca_pem.as_bytes())
        .map_err(|e| format!("CA PEM parse: {}", e))?
        .into_contents();
    let ca_cert_path = out_dir.join("ca.crt");
    std::fs::write(&ca_cert_path, ca_pem.as_bytes()).map_err(|e| format!("write ca.crt: {}", e))?;

    // ---- Server signing key + CSR + cert (signed by root CA) ----
    let server_sign_key =
        Sm2KeyPair::generate().map_err(|e| format!("server sign keygen: {}", e))?;
    let server_sign_pub_65 = server_sign_key.public_key_bytes_uncompressed();
    let server_sign_csr_pem = CsrBuilder::new_sm2("server-sign.local", &server_sign_pub_65)
        .map_err(|e| format!("CsrBuilder server_sign: {}", e))?
        .build_pem(&server_sign_key)
        .map_err(|e| format!("server_sign CSR build_pem: {}", e))?;
    let (_, server_sign_cert_pem) = ca_signer
        .sign_csr_with_profile(
            server_sign_csr_pem.as_bytes(),
            365,
            &gm_ca::profiles::tlcp::tlcp_server_sign_ecc(),
        )
        .map_err(|e| format!("sign_csr_with_profile server_sign: {}", e))?;
    let server_sign_cert_der = pem::parse(server_sign_cert_pem.as_bytes())
        .map_err(|e| format!("PEM parse server_sign.crt: {}", e))?
        .into_contents();

    // ---- Server encryption key + CSR + cert (signed by root CA) ----
    let server_enc_key = Sm2KeyPair::generate().map_err(|e| format!("server enc keygen: {}", e))?;
    let server_enc_pub_65 = server_enc_key.public_key_bytes_uncompressed();
    let server_enc_csr_pem = CsrBuilder::new_sm2("server-enc.local", &server_enc_pub_65)
        .map_err(|e| format!("CsrBuilder server_enc: {}", e))?
        .build_pem(&server_enc_key)
        .map_err(|e| format!("server_enc CSR build_pem: {}", e))?;
    let (_, server_enc_cert_pem) = ca_signer
        .sign_csr_with_profile(
            server_enc_csr_pem.as_bytes(),
            365,
            &gm_ca::profiles::tlcp::tlcp_server_enc_ecc(),
        )
        .map_err(|e| format!("sign_csr_with_profile server_enc: {}", e))?;
    let server_enc_cert_der = pem::parse(server_enc_cert_pem.as_bytes())
        .map_err(|e| format!("PEM parse server_enc.crt: {}", e))?
        .into_contents();

    // ---- Server chain PEM (sign.crt ‖ enc.crt) ----
    let mut chain_pem = String::new();
    chain_pem.push_str(server_sign_cert_pem.as_str());
    chain_pem.push_str(server_enc_cert_pem.as_str());
    let server_chain_path = out_dir.join("server_chain.crt");
    std::fs::write(&server_chain_path, chain_pem.as_bytes())
        .map_err(|e| format!("write server_chain.crt: {}", e))?;

    // ---- Server combined key PEM (sign.key ‖ enc.key) — SEC1
    // unencrypted concatenated. GmSSL 2026-06+ master accepts
    // `BEGIN EC PRIVATE KEY` blocks for `-key` (no PBES2 encryption
    // required). ----
    let server_sign_key_pem = server_sign_key
        .private_key_pem()
        .map_err(|e| format!("server_sign SEC1 PEM: {}", e))?;
    let server_enc_key_pem = server_enc_key
        .private_key_pem()
        .map_err(|e| format!("server_enc SEC1 PEM: {}", e))?;
    let mut combined_key_pem = String::new();
    combined_key_pem.push_str(server_sign_key_pem.as_str());
    combined_key_pem.push_str(server_enc_key_pem.as_str());
    let server_combined_key_path = out_dir.join("server_combined.key");
    std::fs::write(&server_combined_key_path, combined_key_pem.as_bytes())
        .map_err(|e| format!("write server_combined.key: {}", e))?;

    // ---- Client signing key + CSR + cert (signed by root CA) ----
    let client_sign_key =
        Sm2KeyPair::generate().map_err(|e| format!("client sign keygen: {}", e))?;
    let client_sign_pub_65 = client_sign_key.public_key_bytes_uncompressed();
    let client_sign_csr_pem = CsrBuilder::new_sm2("client-sign.local", &client_sign_pub_65)
        .map_err(|e| format!("CsrBuilder client_sign: {}", e))?
        .build_pem(&client_sign_key)
        .map_err(|e| format!("client_sign CSR build_pem: {}", e))?;
    let (_, client_sign_cert_pem) = ca_signer
        .sign_csr_with_profile(
            client_sign_csr_pem.as_bytes(),
            365,
            &gm_ca::profiles::tlcp::tlcp_client_sign_ecc(),
        )
        .map_err(|e| format!("sign_csr_with_profile client_sign: {}", e))?;
    let client_sign_cert_der = pem::parse(client_sign_cert_pem.as_bytes())
        .map_err(|e| format!("PEM parse client_sign.crt: {}", e))?
        .into_contents();

    // ---- Client encryption key + CSR + cert (signed by root CA) ----
    let client_enc_key = Sm2KeyPair::generate().map_err(|e| format!("client enc keygen: {}", e))?;
    let client_enc_pub_65 = client_enc_key.public_key_bytes_uncompressed();
    let client_enc_csr_pem = CsrBuilder::new_sm2("client-enc.local", &client_enc_pub_65)
        .map_err(|e| format!("CsrBuilder client_enc: {}", e))?
        .build_pem(&client_enc_key)
        .map_err(|e| format!("client_enc CSR build_pem: {}", e))?;
    let (_, client_enc_cert_pem) = ca_signer
        .sign_csr_with_profile(
            client_enc_csr_pem.as_bytes(),
            365,
            &gm_ca::profiles::tlcp::tlcp_client_enc_ecc(),
        )
        .map_err(|e| format!("sign_csr_with_profile client_enc: {}", e))?;
    let client_enc_cert_der = pem::parse(client_enc_cert_pem.as_bytes())
        .map_err(|e| format!("PEM parse client_enc.crt: {}", e))?
        .into_contents();

    let client_sign_key_pem = client_sign_key
        .private_key_pem()
        .map_err(|e| format!("client_sign SEC1 PEM: {}", e))?;
    let client_enc_key_pem = client_enc_key
        .private_key_pem()
        .map_err(|e| format!("client_enc SEC1 PEM: {}", e))?;

    Ok(GmcaCerts {
        ca_cert: ca_cert_path,
        server_chain: server_chain_path,
        server_combined_key: server_combined_key_path,
        server_sign_cert_der,
        server_enc_cert_der,
        client_sign_cert_der,
        client_enc_cert_der,
        ca_cert_der,
        client_sign_key_pem,
        client_enc_key_pem,
        server_sign_pub_65,
    })
}

// ---------------------------------------------------------------------------
// GmSSL CLI invocation
// ---------------------------------------------------------------------------

/// `true` iff the `gmssl` CLI is reachable on `PATH`. Skips the
/// interop tests silently otherwise.
fn gmssl_present() -> bool {
    which("gmssl").is_some()
}

fn which(name: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for entry in std::env::split_paths(&path) {
        let candidate = entry.join(name);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

fn gmssl_cipher_suite_name(id: &[u8; 2]) -> Option<&'static str> {
    match *id {
        ECDHE_ECDSA_SM4_GCM_SM3 => Some("TLS_ECDHE_SM4_GCM_SM3"),
        ECC_SM4_GCM_SM3 => Some("TLS_ECC_SM4_GCM_SM3"),
        _ => None,
    }
}

/// Spawn `gmssl tlcp_server` listening on `port` with the given cert
/// paths and cipher suites (in priority order, highest first).
async fn spawn_gmssl_tlcp_server(
    certs: &GmcaCerts,
    port: u16,
    cipher_suites: &[[u8; 2]],
) -> Result<Child, String> {
    if cipher_suites.is_empty() {
        return Err("spawn_gmssl_tlcp_server requires at least one cipher suite".into());
    }
    let mut cmd = tokio::process::Command::new("gmssl");
    cmd.arg("tlcp_server")
        .arg("-port")
        .arg(port.to_string())
        .arg("-cert")
        .arg(&certs.server_chain)
        .arg("-key")
        .arg(&certs.server_combined_key)
        .arg("-cacert")
        .arg(&certs.ca_cert)
        .arg("-verbose")
        .stderr(Stdio::piped())
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .kill_on_drop(true);
    for suite in cipher_suites {
        let name = gmssl_cipher_suite_name(suite).ok_or_else(|| {
            format!(
                "no GmSSL name for cipher suite ID {:02x}{:02x}",
                suite[0], suite[1]
            )
        })?;
        cmd.arg("-cipher_suite").arg(name);
    }
    let child = cmd
        .spawn()
        .map_err(|e| format!("spawn gmssl tlcp_server: {}", e))?;
    eprintln!("[gm-ca] spawned gmssl tlcp_server pid={:?}", child.id());
    Ok(child)
}

/// Wait for a TCP port to start accepting connections. Polls every
/// 50 ms up to `timeout`.
async fn wait_for_port(port: u16, timeout: Duration) -> Result<(), String> {
    let addr = SocketAddr::from(([127, 0, 0, 1], port));
    let start = std::time::Instant::now();
    while start.elapsed() < timeout {
        match tokio::net::TcpStream::connect(addr).await {
            Ok(s) => {
                drop(s);
                return Ok(());
            }
            Err(_) => tokio::time::sleep(Duration::from_millis(50)).await,
        }
    }
    Err(format!("port {port} not listening after {:?}", timeout))
}

fn pick_free_port() -> u16 {
    // Bind to port 0 to let the OS allocate a free port, then read
    // it back. Avoids a race vs. arbitrary ports being in use.
    let listener =
        std::net::TcpListener::bind(("127.0.0.1", 0)).expect("bind port 0 for pick_free_port");
    let port = listener.local_addr().expect("local_addr").port();
    drop(listener);
    port
}

async fn dump_gmssl_stderr(child: &mut Child) -> String {
    let mut buf = String::new();
    if let Some(mut stderr) = child.stderr.take() {
        let _ = stderr.read_to_string(&mut buf).await;
    }
    buf
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// Mode A — `gmssl tlcp_server` accepts a gm-ca-signed client cert
/// during an ECDHE-ECDSA SM4-GCM-SM3 handshake.
///
/// Proves: gm-ca's wire-format X.509 SM2 SPKI / sm3WithSM2
/// signature / SM3[:20] SKI / SM3[:20] AKI all chain-walk correctly
/// against GmSSL's `tls_recv_client_certificate` → `x509_certs_verify
/// _tlcp` path on the SM4-GCM-SM3 ECDHE suite.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_server_gmca_client_ecdhe_gcm() {
    if !gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    let tmp = std::env::temp_dir().join(format!("gm-ca-gmssl-interop-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    let certs = generate_gmca_test_certs(&tmp).expect("generate_test_certs");
    eprintln!("[gm-ca] cert dir: {}", tmp.display());

    let port = pick_free_port();
    let mut server = spawn_gmssl_tlcp_server(&certs, port, TLCP_CIPHER_SUITES)
        .await
        .expect("spawn gmssl");
    wait_for_port(port, Duration::from_secs(5))
        .await
        .expect("server to start listening");

    // Configure the gm-tlcp connector with the gm-ca-signed client
    // chain `[client_sign, client_enc, root_ca]` + the server's
    // 65-byte SM2 sign pubkey for ECDHE verification.
    let connector = TlcpConnector::new()
        .with_server_sign_key(
            certs.server_sign_pub_65.clone(),
            GMSSL_DEFAULT_DISTID.to_string(),
        )
        .with_client_certs(
            vec![
                certs.client_sign_cert_der.clone(),
                certs.client_enc_cert_der.clone(),
                certs.ca_cert_der.clone(),
            ],
            certs.client_sign_key_pem.clone(),
            Some(certs.client_enc_key_pem.clone()),
            None,
        )
        .with_cipher_suites(vec![ECDHE_ECDSA_SM4_GCM_SM3]);

    let addr = SocketAddr::from(([127, 0, 0, 1], port));
    let tcp = TcpStream::connect(addr).await.expect("TCP connect");
    let mut client = connector
        .connect_with_certs(tcp)
        .await
        .expect("TLCP handshake as client (gm-ca cert, gmssl server)");
    eprintln!(
        "[gm-ca] E051 handshake OK; negotiated suite = {:?}",
        client.cipher_suite()
    );

    // Brief sleep to let GmSSL's record loop drain its
    // post-`Finished` state into the app-data select loop. (Same
    // convention as gm-tlcp/tests/gmssl_interop.rs.)
    tokio::time::sleep(Duration::from_millis(200)).await;
    let payload = b"GET / HTTP/1.0\r\nHost: gm-ca\r\n\r\n";
    client
        .write_application_data(payload)
        .await
        .expect("client write");
    let response = client.read_application_data().await.expect("client read");
    assert!(
        response.len() >= payload.len(),
        "echoed response too short: got {} bytes",
        response.len()
    );
    assert_eq!(&response[..payload.len()], payload);

    client.close().await.expect("client close_notify");

    // Surface gmssl's verbose stderr if the test failed — useful for
    // debugging the `tls_recv_client_certificate` chain walk.
    if std::env::var_os("GMCA_INTEROP_DUMP_GMSSL").is_some() {
        eprintln!(
            "=== gmssl stderr ===\n{}",
            dump_gmssl_stderr(&mut server).await
        );
    }
    drop(server);

    eprintln!("gm-ca × gmssl interop (E051): PASS");
}

/// Mode A — same direction but on the static-ECDH suite
/// (TLS_ECC_SM4_GCM_SM3). The cipher-suite byte changes which
/// static-key path gm-tlcp walks but the cert-verification path
/// through `x509_certs_verify_tlcp` is the same as E051.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_server_gmca_client_ecc_gcm() {
    if !gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    let tmp = std::env::temp_dir().join(format!("gm-ca-gmssl-interop-ecc-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    let certs = generate_gmca_test_certs(&tmp).expect("generate_test_certs");

    let port = pick_free_port();
    let server = spawn_gmssl_tlcp_server(&certs, port, &[ECC_SM4_GCM_SM3])
        .await
        .expect("spawn gmssl");
    wait_for_port(port, Duration::from_secs(5))
        .await
        .expect("server to start listening");

    let connector = TlcpConnector::new()
        .with_server_sign_key(
            certs.server_sign_pub_65.clone(),
            GMSSL_DEFAULT_DISTID.to_string(),
        )
        .with_client_certs(
            vec![
                certs.client_sign_cert_der.clone(),
                certs.client_enc_cert_der.clone(),
                certs.ca_cert_der.clone(),
            ],
            certs.client_sign_key_pem.clone(),
            Some(certs.client_enc_key_pem.clone()),
            None,
        )
        .with_cipher_suites(vec![ECC_SM4_GCM_SM3]);

    let addr = SocketAddr::from(([127, 0, 0, 1], port));
    let tcp = TcpStream::connect(addr).await.expect("TCP connect");
    let mut client = connector
        .connect_with_certs(tcp)
        .await
        .expect("TLCP handshake as client (gm-ca cert, gmssl server, E053)");
    eprintln!(
        "[gm-ca] E053 handshake OK; negotiated suite = {:?}",
        client.cipher_suite()
    );

    tokio::time::sleep(Duration::from_millis(200)).await;
    let payload = b"GET / HTTP/1.0\r\nHost: gm-ca\r\n\r\n";
    client
        .write_application_data(payload)
        .await
        .expect("client write");
    let response = client.read_application_data().await.expect("client read");
    assert!(
        response.len() >= payload.len(),
        "echoed response too short: got {} bytes",
        response.len()
    );
    assert_eq!(&response[..payload.len()], payload);

    client.close().await.expect("client close_notify");
    drop(server);
    eprintln!("gm-ca × gmssl interop (E053): PASS");
}

// ---------------------------------------------------------------------------
// Wire-format introspection
// ---------------------------------------------------------------------------

/// Confirms gm-ca's emitted client cert is shape-compatible with
/// GmSSL's verifier by parsing the leaf through `x509-parser` and
/// checking the SPKI algorithm OID + signatureAlgorithm OID match
/// the values GmSSL master looks for (1.2.156.10197.1.301 and
/// 1.2.156.10197.1.501).
#[test]
#[ignore = "cert hierarchy generation is fast but the test exercises x509-parser DER; keep ignored by default"]
fn gmca_issued_client_cert_has_expected_sm2_spki_and_sig_alg() {
    use x509_parser::certificate::X509Certificate;
    use x509_parser::prelude::FromDer;

    let tmp = std::env::temp_dir().join(format!("gm-ca-wire-introspect-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    let certs = generate_gmca_test_certs(&tmp).expect("generate_test_certs");

    let (_, leaf) =
        X509Certificate::from_der(&certs.client_sign_cert_der).expect("client_sign.crt parse");

    let spki_oid = leaf.public_key().algorithm.algorithm.as_bytes();
    let sig_alg_oid = leaf.signature_algorithm.algorithm.as_bytes();

    // 1.2.156.10197.1.301 (SM2 public key OID)
    const SM2_PK_OID: &[u8] = &[0x2A, 0x8C, 0xD8, 0xE3, 0x65, 0x6A, 0x01, 0x01];
    // 1.2.156.10197.1.501 (sm3WithSM2 signature OID)
    const SM2_SIG_OID: &[u8] = &[0x2A, 0x8C, 0xD8, 0xE3, 0x65, 0x6A, 0x02, 0x01, 0xF5];

    assert_eq!(
        spki_oid, SM2_PK_OID,
        "client_sign cert SPKI OID must be SM2 (1.2.156.10197.1.301)"
    );
    assert_eq!(
        sig_alg_oid, SM2_SIG_OID,
        "client_sign cert signatureAlgorithm OID must be sm3WithSM2 (1.2.156.10197.1.501)"
    );
}
