//! GmSSL interop integration test.
//!
//! Drives a full TLCP handshake between this crate (as client) and a
//! locally-launched `gmssl tlcp_server` (as server), then exchanges
//! application data over the encrypted channel.
//!
//! **Skip condition**: this test is `#[ignore]`d by default and runs
//! only when explicitly enabled via
//!
//! ```bash
//! cargo test -p gm-tlcp --test gmssl_interop -- --ignored
//! ```
//!
//! It also self-skips when the `gmssl` binary is not available, so
//! the rest of the test suite is unaffected.
//!
//! **What it validates end-to-end**:
//!   1. Cipher suite negotiation: at least one of the four TLCP
//!      suites is mutually supported (we ship the same four IDs that
//!      GmSSL 3.x advertises).
//!   2. ServerKeyExchange signature verification using the 65-byte
//!      uncompressed SM2 public key extracted from the cert.
//!   3. Master secret derivation matches both sides (verified
//!      implicitly by Finished message verification on both sides).
//!   4. ECDHE-SM4-GCM-SM3 / ECDHE-SM4-CBC-SM3 application data is
//!      successfully encrypted and decrypted in both directions.

use std::process::Stdio;
use std::time::Duration;

use tokio::net::{TcpListener, TcpStream};
use tokio::process::Child;

use gm_tlcp::tlcp::{
    TLS_ECC_SM4_CBC_SM3, TLS_ECC_SM4_GCM_SM3, TLS_ECDHE_SM4_CBC_SM3, TLS_ECDHE_SM4_GCM_SM3,
    TlcpAcceptor, TlcpCipherSuite, TlcpConnector,
};

mod support;

/// All four TLCP cipher suites, in the same preference order that
/// GmSSL advertises them.
const TLCP_CIPHER_SUITES: &[[u8; 2]] = &[
    TLS_ECDHE_SM4_GCM_SM3,
    TLS_ECDHE_SM4_CBC_SM3,
    TLS_ECC_SM4_GCM_SM3,
    TLS_ECC_SM4_CBC_SM3,
];

/// Default distid used by `gmssl certgen` (and matching client verify).
const GMSSL_DEFAULT_DISTID: &str = "1234567812345678";

/// Path to the GmSSL `tlcp_server` binary on PATH.
fn gmssl_path() -> std::path::PathBuf {
    std::path::PathBuf::from("gmssl")
}

/// Map a TLCP cipher-suite ID (the 2-byte wire value we use) to the
/// GmSSL CLI's name string. Used for `-cipher_suite` arguments passed
/// to `gmssl tlcp_server`.
fn gmssl_cipher_suite_name(id: &[u8; 2]) -> Option<&'static str> {
    match *id {
        TLS_ECDHE_SM4_GCM_SM3 => Some("TLS_ECDHE_SM4_GCM_SM3"),
        TLS_ECDHE_SM4_CBC_SM3 => Some("TLS_ECDHE_SM4_CBC_SM3"),
        TLS_ECC_SM4_GCM_SM3 => Some("TLS_ECC_SM4_GCM_SM3"),
        TLS_ECC_SM4_CBC_SM3 => Some("TLS_ECC_SM4_CBC_SM3"),
        _ => None,
    }
}

/// Build a [`TlcpConnector`] configured to interop cleanly with
/// GmSSL 2026-06+ master, which sends a `CertificateRequest` after
/// ServerKeyExchange for all ECDHE_*_SM4_* suites.
///
/// Concretely this means:
///
///   1. The server's sign pubkey (extracted 65-byte SEC1) and distid
///      are configured via `with_server_sign_key`.
///
///   2. The client cert chain `[sign, enc, CA]` is configured via
///      `with_client_certs` — leaf-first so that GmSSL's
///      `x509_certs_verify_tlcp` walk has the CA cert in hand to
///      verify both entity certs against. GmSSL's AKI generated by
///      `gmssl reqsign` lacks the `directory_name` required by the
///      fallback `x509_cert_chain_find_root_ca_cert` path, so the CA
///      MUST be in the chain itself.
///
///   3. The unencrypted client sign and enc SEC1 PEMs are passed in
///      alongside the standard SM3-PBKDF2 password. The encrypted
///      PKCS#8 PEMs that GmSSL emits are decoded via
///      `support::gmssl_key` before being re-serialized.
///
/// The optional `offer` restricts the offered cipher suites; if `None`,
/// all four TLCP suites are offered (matching the connector default).
fn build_gmssl_compatible_connector(
    certs: &support::cert_setup::GmsslCerts,
    offer: Option<&[[u8; 2]]>,
) -> TlcpConnector {
    let client_sign_pem =
        std::fs::read_to_string(&certs.client_key_unenc).expect("read client.key.unenc.pem");
    // The client also needs its long-term encryption private key for
    // the GB/T 32918-2017 §6.4.2 SM2 key agreement (TLCP ECDHE PMS).
    // GmSSL master's `sm2_key_exchange` reads the static public from
    // the CLIENT's *encryption* cert (chain index 1) — see
    // `tlcp_recv_client_key_exchange` → `x509_certs_get_cert_by_index
    // (..., 1, ...)`. So our connector must use the matching
    // `client.enc.key` private, not the sign key.
    let client_enc_key_pem = {
        // The encrypted PKCS#8 PEM uses GmSSL's PBES2 envelope
        // (SM3-PBKDF2 + SM4-CBC), which the standard pkcs8 crate
        // can't read. Decrypt via the test-only helper in
        // `gmssl_key`, then re-serialize as SEC1 for `gm-crypto`'s
        // PKCS#8/SEC1 loader.
        let enc_kp = support::gmssl_key::load_sm2_key_from_gmssl_pem(
            &certs.client_enc_key,
            support::cert_setup::DEFAULT_PASSWORD,
        )
        .expect("decrypt client.enc.key");
        Some(enc_kp.private_key_pem().expect("client enc SEC1 PEM"))
    };
    let client_enc_cert_der =
        support::cert_setup::read_pem_to_der(&certs.client_enc_crt, "CERTIFICATE")
            .expect("decode client.enc.crt PEM");
    let client_ca_cert_der = support::cert_setup::read_pem_to_der(&certs.ca_cert, "CERTIFICATE")
        .expect("decode ca.crt PEM");

    let mut connector = TlcpConnector::new();
    connector =
        connector.with_server_sign_key(certs.sign_pub_65.clone(), GMSSL_DEFAULT_DISTID.to_string());
    connector = connector.with_client_certs(
        vec![
            certs.client_cert_der.clone(),
            client_enc_cert_der,
            client_ca_cert_der,
        ],
        client_sign_pem,
        client_enc_key_pem,
        Some(support::cert_setup::DEFAULT_PASSWORD.to_string()),
    );
    if let Some(suites) = offer {
        connector = connector.with_cipher_suites(suites.to_vec());
    }
    connector
}

/// Spawn `gmssl tlcp_server` listening on the given port with the
/// given cert/key paths and the given cipher suites (in priority
/// order, highest first). Returns the `Child` so the caller can kill
/// it when the test ends.
///
/// # GmSSL master (2026-06+) notes
///
/// - `-ex_key` / `-ex_pass` were removed; a single `-key` PEM file
///   containing BOTH sign and enc keys (concatenated) is required.
///   See [`GmsslCerts::combined_key`].
/// - `-cipher_suite` is mandatory in master and may appear multiple
///   times to express server preference order. `-cipher_suite` names
///   must come from GmSSL's own `tls_cipher_suite_from_name` table.
///
/// On error during startup, the captured stderr is read back into a
/// debug string for the test report so a passing `-verbose` trace
/// survives even when the test fails.
async fn spawn_gmssl_tlcp_server(
    certs: &support::cert_setup::GmsslCerts,
    port: u16,
    cipher_suites: &[[u8; 2]],
) -> Result<Child, String> {
    if cipher_suites.is_empty() {
        return Err("spawn_gmssl_tlcp_server requires at least one cipher suite".into());
    }
    let mut cmd = tokio::process::Command::new(gmssl_path());
    cmd.arg("tlcp_server")
        .arg("-port")
        .arg(port.to_string())
        .arg("-cert")
        .arg(&certs.chain_crt)
        .arg("-key")
        .arg(&certs.combined_key)
        .arg("-pass")
        .arg(support::cert_setup::DEFAULT_PASSWORD)
        .arg("-cacert")
        .arg(&certs.ca_cert)
        .arg("-verbose")
        // Persist gmssl's full verbose trace so post-mortem debugging
        // doesn't lose data when the test process tears down the
        // pipe-to-tokio reader at the end of the suite.
        .stderr(std::process::Stdio::from(
            std::fs::File::create(format!("/tmp/gm-tlcp-server-{}.log", std::process::id()))
                .expect("create gmssl stderr log"),
        ))
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .kill_on_drop(true);
    for suite in cipher_suites {
        let name = gmssl_cipher_suite_name(suite).ok_or_else(|| {
            format!(
                "no GmSSL name for cipher suite ID {:02x}{:02x}",
                suite[0], suite[1]
            )
        })?;
        cmd.arg("-cipher_suite").arg(name);
    }
    let child = cmd
        .spawn()
        .map_err(|e| format!("spawn gmssl tlcp_server: {}", e))?;
    eprintln!("[gm-tlcp] spawned gmssl tlcp_server pid={:?}", child.id());
    Ok(child)
}

/// Spawn `gmssl tlcp_client` connecting to `host:port`. Passes the
/// sign cert as `-cacert` so GmSSL's optional cert chain verification
/// succeeds against our self-signed certs.
async fn spawn_gmssl_tlcp_client(
    certs: &support::cert_setup::GmsslCerts,
    host: &str,
    port: u16,
) -> Result<Child, String> {
    let mut cmd = tokio::process::Command::new(gmssl_path());
    cmd.arg("tlcp_client")
        .arg("-host")
        .arg(host)
        .arg("-port")
        .arg(port.to_string())
        .arg("-cacert")
        .arg(&certs.sign_cert)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .kill_on_drop(true);
    let child = cmd
        .spawn()
        .map_err(|e| format!("spawn gmssl tlcp_client: {}", e))?;
    eprintln!("[gm-tlcp] spawned gmssl tlcp_client pid={:?}", child.id());
    Ok(child)
}

/// Wait until the given TCP port accepts connections (max ~5s).
async fn wait_for_port(port: u16) -> Result<(), String> {
    let deadline = std::time::Instant::now() + Duration::from_secs(5);
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    loop {
        if std::time::Instant::now() >= deadline {
            return Err(format!("port {} never opened", port));
        }
        match TcpStream::connect(addr).await {
            Ok(s) => {
                drop(s);
                return Ok(());
            }
            Err(_) => tokio::time::sleep(Duration::from_millis(50)).await,
        }
    }
}

/// Find a free TCP port.
fn pick_free_port() -> u16 {
    // Bind to port 0 to let the OS pick, then drop the socket.
    let l = std::net::TcpListener::bind("127.0.0.1:0").expect("bind port 0");
    let port = l.local_addr().unwrap().port();
    drop(l);
    port
}

#[tokio::test]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_tlcp_handshake_and_app_data() {
    if !support::cert_setup::gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    // 1. Generate fresh test certs under a temp dir.
    let tmp = std::env::temp_dir().join(format!("gm-tlcp-interop-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    let certs = support::cert_setup::generate_test_certs(&tmp).expect("generate test certs");
    // Keep the temp dir around after the test for offline inspection.
    eprintln!("[gm-tlcp] cert dir: {}", tmp.display());

    // 2. Spawn the GmSSL tlcp_server on a free port.
    let port = pick_free_port();
    let mut server = spawn_gmssl_tlcp_server(&certs, port, TLCP_CIPHER_SUITES)
        .await
        .expect("spawn gmssl");
    wait_for_port(port)
        .await
        .expect("server to start listening");
    eprintln!("[gm-tlcp] gmssl listening on port {}", port);

    // gmssl's verbose stderr is now redirected to
    // `/tmp/gm-tlcp-server-<pid>.log` (see `spawn_gmssl_tlcp_server`)
    // so the trace survives even if the test panics and our
    // async stderr reader never finishes.
    eprintln!(
        "[gm-tlcp] gmssl verbose log: /tmp/gm-tlcp-server-{}.log",
        std::process::id()
    );

    // 3. Build the TLCP connector with the server's sign public key
    // and the client certificate chain (signing cert + CA cert, in
    // leaf-first order). The latter is required by GmSSL 2026-06+
    // master, which forces a CertificateRequest for ECDHE suites.
    let mut connector = build_gmssl_compatible_connector(&certs, Some(TLCP_CIPHER_SUITES));

    // 4. Connect.
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    let tcp = TcpStream::connect(addr).await.expect("TCP connect");
    let mut client = connector
        .connect_with_certs(tcp)
        .await
        .expect("TLCP handshake as client");
    eprintln!(
        "client handshake OK; negotiated suite = {:?}",
        client.cipher_suite()
    );

    // 5. Exchange application data.
    let request = b"GET / HTTP/1.0\r\nHost: localhost\r\n\r\n";
    // Brief sleep to let the gmssl server fully enter its data-loop state
    // after sending its Finished. Without this, the first app-data write
    // can race the server's transition from `do_handshake_select` to the
    // app-data select loop. Sampling reveals that the gmssl master
    // server (3.3.0-dev) transiently stalls in `do_send_select -> __select`
    // immediately after `tlcp_do_accept` returns 1; the pre-write sleep
    // gives the server time to reach the data-loop `select(fd, READ)`
    // before we drop our first 64-byte record into the kernel buffer.
    // Empirically 500ms is enough on this macOS host; 100ms is the
    // boundary at which the test starts flaking on slower CI runners.
    tokio::time::sleep(std::time::Duration::from_millis(500)).await;
    client
        .write_application_data(request)
        .await
        .expect("client write");
    let response = client.read_application_data().await.expect("client read");
    // GmSSL echoes back what we send. Verify we got at least our request bytes.
    assert!(
        response.len() >= request.len(),
        "echoed response too short: got {} bytes",
        response.len()
    );
    assert_eq!(&response[..request.len()], request);

    // 6. Clean shutdown of the client side. Don't kill the server yet
    //    — we want to verify the server still has a clean connection.
    client.close().await.expect("client close_notify");

    // 7. Now build the server side too: use the same connector / accept
    //    pattern so that we exercise BOTH directions. (GmSSL already
    //    ran the server, this would be testing two clients against
    //    two servers. Skip; one direction is enough to catch obvious
    //    interop failures.)
    drop(server);

    eprintln!("GmSSL interop: PASS");
}

#[tokio::test]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_tlcp_handshake_with_all_suites() {
    if !support::cert_setup::gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    for &suite_id in TLCP_CIPHER_SUITES {
        let suite = TlcpCipherSuite::from_id(suite_id)
            .unwrap_or_else(|| panic!("unknown suite {:?}", suite_id));

        let tmp = std::env::temp_dir().join(format!(
            "gm-tlcp-interop-{}-{:02x}{:02x}",
            std::process::id(),
            suite_id[0],
            suite_id[1]
        ));
        let _ = std::fs::remove_dir_all(&tmp);
        let certs = support::cert_setup::generate_test_certs(&tmp).expect("generate test certs");

        let port = pick_free_port();
        let server = spawn_gmssl_tlcp_server(&certs, port, TLCP_CIPHER_SUITES)
            .await
            .expect("spawn gmssl");
        wait_for_port(port)
            .await
            .expect("server to start listening");

        // Connector with full client-cert chain (required by GmSSL
        // 2026-06+ master for all ECDHE_*_SM4_* suites) offering
        // ONLY this one suite so we know which one is negotiated.
        let mut connector = build_gmssl_compatible_connector(&certs, Some(&[suite_id][..]));

        let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
        let tcp = TcpStream::connect(addr).await.expect("TCP connect");
        let mut client = connector
            .connect_with_certs(tcp)
            .await
            .unwrap_or_else(|e| panic!("handshake for suite {:?} failed: {}", suite_id, e));

        assert_eq!(
            client.cipher_suite().id,
            suite_id,
            "expected suite {:?} to be negotiated",
            suite_id
        );

        client
            .write_application_data(b"PING")
            .await
            .expect("client write");
        let buf = client.read_application_data().await.expect("client read");
        assert_eq!(&buf, b"PING", "suite {:?} round-trip mismatch", suite_id);

        client.close().await.expect("close");
        drop(server);

        eprintln!("suite {:?} ({:?}): PASS", suite_id, suite.name);
    }
}

// ============================================================================
// COMPREHENSIVE INTEROP COVERAGE
// ============================================================================
// The two tests above exercise (i) gm-tlcp as CLIENT against a GmSSL
// tlcp_server, and (ii) each of the four TLCP cipher suites in isolation.
// That leaves several important paths unverified:
//
//   * Whether gm-tlcp also works correctly as a SERVER when a GmSSL
//     tlcp_client initiates the handshake.
//   * Whether APP_DATA larger than the 16 KiB record limit is correctly
//     fragmented on the write side and reassembled on the read side.
//   * Whether a handshake with no mutually-supported cipher suite fails
//     cleanly (rather than silently picking a default).
//   * Whether server-side cipher suite selection honors client preference
//     order (the spec says: take the first suite from the client's list
//     that the server supports).
//   * Whether two consecutive handshakes on the same TcpListener are
//     cleanly isolated (no session-state leakage between sessions).
//
// The five tests below close these gaps.
// ============================================================================

/// **A. Reverse direction: gm-tlcp SERVER ↔ GmSSL CLIENT**
///
/// Drives a full TLCP handshake where gm-tlcp plays the server role
/// (TlcpAcceptor) and the locally-spawned `gmssl tlcp_client` plays the
/// client role. This validates:
///   * `TlcpAcceptor::accept_with_certs` end-to-end
///   * Server-side ECDHE ServerKeyExchange **generation + signing**
///     (the corresponding verification path on the gm-tlcp client side
///     is already covered by the tests above)
///   * Server-side Finished message **construction**
///   * Server-side processing of the client's ClientKeyExchange
///     (ephemeral ECDHE pubkey for ECDHE suites; encrypted PMS for ECC)
#[tokio::test]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_tlcp_client_to_gm_tlcp_server() {
    if !support::cert_setup::gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    // Generate certs + keys
    let tmp = std::env::temp_dir().join(format!("gm-tlcp-reverse-{}-{}", std::process::id(), "A"));
    let _ = std::fs::remove_dir_all(&tmp);
    let certs = support::cert_setup::generate_test_certs(&tmp).expect("generate test certs");

    // Load sign + enc keys from gmssl's SM3-PBKDF2-encrypted PKCS#8 PEM.
    // The standard `Sm2KeyPair::from_encrypted_pem` only handles
    // SHA-1/SHA-2 PRFs and AES ciphers (it's built on the pkcs8
    // crate, whose EncryptionScheme enum has no SM4 variant), so we
    // use the test-only helper in `support::gmssl_key` that
    // implements SM3-PBKDF2 + SM4-CBC decryption ourselves.
    let sign_key = support::gmssl_key::load_sm2_key_from_gmssl_pem(
        &certs.sign_key,
        support::cert_setup::DEFAULT_PASSWORD,
    )
    .expect("decrypt sign.key");
    let enc_key = support::gmssl_key::load_sm2_key_from_gmssl_pem(
        &certs.enc_key,
        support::cert_setup::DEFAULT_PASSWORD,
    )
    .expect("decrypt enc.key");

    // Bind a TcpListener and pick the port up front.
    let listener = TcpListener::bind("127.0.0.1:0").await.expect("bind");
    let port = listener.local_addr().expect("local_addr").port();

    // Spawn gmssl tlcp_client connecting to us.
    let mut gmssl_client = spawn_gmssl_tlcp_client(&certs, "127.0.0.1", port)
        .await
        .expect("spawn gmssl tlcp_client");

    // Drain stderr for debug visibility.
    if let Some(mut stderr) = gmssl_client.stderr.take() {
        tokio::spawn(async move {
            use tokio::io::AsyncBufReadExt;
            let mut reader = tokio::io::BufReader::new(&mut stderr);
            let mut line = String::new();
            while reader.read_line(&mut line).await.unwrap_or(0) > 0 {
                eprintln!("[gmssl client stderr] {}", line.trim_end());
                line.clear();
            }
        });
    }

    // Accept the connection, run the server-side handshake.
    let (tcp, _peer) = listener.accept().await.expect("accept");
    let acceptor = TlcpAcceptor::new().with_dual_certs(
        certs.sign_cert_der.clone(),
        certs.enc_cert_der.clone(),
        sign_key,
        enc_key,
    );
    let mut server = acceptor
        .accept_with_certs(tcp)
        .await
        .expect("TLCP handshake as server");
    eprintln!(
        "[gm-tlcp] server handshake OK; negotiated suite = {:?}",
        server.cipher_suite()
    );

    // gmssl tlcp_client sends a pre-canned HTTP-like request then
    // reads an echo. We mirror that: read what it sent, echo it back.
    let req = server
        .read_application_data()
        .await
        .expect("server read request");
    assert!(!req.is_empty(), "gmssl client should have sent something");
    server
        .write_application_data(&req)
        .await
        .expect("server echo");

    // Close cleanly. gmssl should detect EOF / close_notify and exit.
    server.close().await.expect("server close_notify");

    // Confirm gmssl exited successfully.
    let status = gmssl_client.wait().await.expect("wait gmssl client");
    assert!(
        status.success(),
        "gmssl tlcp_client exited with failure: {:?}",
        status
    );

    eprintln!("reverse-direction (gm-tlcp SERVER ↔ GmSSL CLIENT): PASS");
}

/// **B. Large APP_DATA crossing record boundaries**
///
/// TLCP record payload is capped at 16 KiB. A 64 KiB write must be
/// split into 4+ records on the writer side and reassembled on the
/// reader side. This test exercises:
///   * `write_application_data` fragmenting a 64 KiB payload
///   * `read_application_data` reassembling the fragments
///   * GCM nonce_explicit incrementing per record
///   * GCM AEAD authentication over each record independently
///   * CBC (next test below) handles padding + HMAC correctly per record
#[tokio::test]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_tlcp_large_app_data() {
    if !support::cert_setup::gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    let tmp = std::env::temp_dir().join(format!("gm-tlcp-large-{}-{}", std::process::id(), "B"));
    let _ = std::fs::remove_dir_all(&tmp);
    let certs = support::cert_setup::generate_test_certs(&tmp).expect("generate test certs");

    let port = pick_free_port();
    let server = spawn_gmssl_tlcp_server(&certs, port, TLCP_CIPHER_SUITES)
        .await
        .expect("spawn gmssl");
    wait_for_port(port).await.expect("server listening");

    // 64 KiB: must span ≥4 TLCP records (record_payload_max = 16384).
    let payload: Vec<u8> = (0..(64 * 1024)).map(|i| (i & 0xFF) as u8).collect();

    let mut connector = build_gmssl_compatible_connector(&certs, Some(TLCP_CIPHER_SUITES));

    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    let tcp = TcpStream::connect(addr).await.expect("TCP connect");
    let mut client = connector
        .connect_with_certs(tcp)
        .await
        .expect("TLCP handshake");

    client
        .write_application_data(&payload)
        .await
        .expect("write 64 KiB");

    // Read until we've recovered the full payload. GmSSL's tlcp_server
    // echoes data byte-for-byte, so the response length should equal
    // the request length exactly.
    let mut received = Vec::with_capacity(payload.len());
    while received.len() < payload.len() {
        let chunk = client.read_application_data().await.expect("read chunk");
        assert!(!chunk.is_empty(), "GmSSL closed mid-stream");
        received.extend_from_slice(&chunk);
    }
    assert_eq!(
        received.len(),
        payload.len(),
        "expected {} bytes, got {}",
        payload.len(),
        received.len()
    );
    assert_eq!(received, payload, "large payload round-trip mismatch");

    client.close().await.expect("close");
    drop(server);

    eprintln!("large-APP_DATA (64 KiB across records): PASS");
}

/// **C. Cipher suite mismatch (negative path)**
///
/// Offers only an unknown suite code point. The server must reject
/// the handshake. We verify that gm-tlcp surfaces a meaningful error
/// (not a panic, not a silent fallback to a default).
#[tokio::test]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_tlcp_no_common_cipher_suite() {
    if !support::cert_setup::gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    let tmp = std::env::temp_dir().join(format!("gm-tlcp-nosuite-{}-{}", std::process::id(), "C"));
    let _ = std::fs::remove_dir_all(&tmp);
    let certs = support::cert_setup::generate_test_certs(&tmp).expect("generate test certs");

    let port = pick_free_port();
    let server = spawn_gmssl_tlcp_server(&certs, port, TLCP_CIPHER_SUITES)
        .await
        .expect("spawn gmssl");
    wait_for_port(port).await.expect("server listening");

    let mut connector = TlcpConnector::new();
    connector =
        connector.with_server_sign_key(certs.sign_pub_65.clone(), GMSSL_DEFAULT_DISTID.to_string());
    // Offer ONLY an unknown suite. `with_cipher_suites` rejects empty
    // lists, so we use a single 0xFFFF marker.
    connector = connector.with_cipher_suites(vec![[0xFF, 0xFF]]);

    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    let tcp = TcpStream::connect(addr).await.expect("TCP connect");
    let result = connector.connect_with_certs(tcp).await;
    let err = match result {
        Ok(_) => panic!("handshake with no mutually-supported suite MUST fail, but it returned Ok"),
        Err(e) => e,
    };
    let msg = format!("{:?}", err).to_lowercase();
    // We don't pin the exact message format, but it should clearly
    // signal a handshake / alert / cipher-suite failure rather than
    // a generic I/O error.
    assert!(
        msg.contains("cipher")
            || msg.contains("suite")
            || msg.contains("alert")
            || msg.contains("handshake"),
        "error message should mention cipher/suite/alert/handshake: {}",
        msg
    );

    drop(server);
    eprintln!("no-common-cipher-suite (negative path): PASS ({})", msg);
}

/// **E. Server-side cipher suite selection semantics**
///
/// The TLCP spec (GB/T 38636-2020) says the server picks the first
/// cipher suite from the client's list that it supports. We verify
/// gm-tlcp honors this by offering [CBC, GCM] and [GCM, CBC] in turn
/// and checking that the negotiated suite is the first one in each
/// client offer.
///
/// We restrict to ECDHE suites only so the test exercises a single
/// cipher-mode axis (CBC vs GCM).
#[tokio::test]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_tlcp_cipher_suite_preference() {
    if !support::cert_setup::gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    struct PreferenceCase {
        label: &'static str,
        offer: [[u8; 2]; 2],
        expected: [u8; 2],
    }
    let cases = &[
        PreferenceCase {
            label: "CBC-then-GCM -> expect ECDHE_CBC",
            offer: [TLS_ECDHE_SM4_CBC_SM3, TLS_ECDHE_SM4_GCM_SM3],
            expected: TLS_ECDHE_SM4_CBC_SM3,
        },
        PreferenceCase {
            label: "GCM-then-CBC -> expect ECDHE_GCM",
            offer: [TLS_ECDHE_SM4_GCM_SM3, TLS_ECDHE_SM4_CBC_SM3],
            expected: TLS_ECDHE_SM4_GCM_SM3,
        },
    ];

    for case in cases {
        let tmp = std::env::temp_dir().join(format!(
            "gm-tlcp-pref-{}-{}-{:02x}{:02x}",
            std::process::id(),
            "E",
            case.offer[0][0],
            case.offer[0][1]
        ));
        let _ = std::fs::remove_dir_all(&tmp);
        let certs = support::cert_setup::generate_test_certs(&tmp).expect("generate test certs");

        let port = pick_free_port();
        let server = spawn_gmssl_tlcp_server(&certs, port, &case.offer)
            .await
            .expect("spawn gmssl");
        wait_for_port(port).await.expect("server listening");

        // Connector with full client-cert chain (required by GmSSL
        // 2026-06+ master for all ECDHE_*_SM4_* suites) offering the
        // case's specific suite list so we can observe preference
        // semantics.
        let mut connector = build_gmssl_compatible_connector(&certs, Some(&case.offer));

        let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
        let tcp = TcpStream::connect(addr).await.expect("TCP connect");
        let client = connector
            .connect_with_certs(tcp)
            .await
            .unwrap_or_else(|e| panic!("{}: handshake failed: {}", case.label, e));

        assert_eq!(
            client.cipher_suite().id,
            case.expected,
            "{}: client offered {:?}, but server picked {:?}",
            case.label,
            case.offer,
            client.cipher_suite().id,
        );
        // No round-trip data needed — we're checking negotiation.
        drop(client);
        drop(server);

        eprintln!("preference ({}): PASS", case.label);
    }
}

/// **F. Multiple sequential handshakes on the same listener**
///
/// Runs 3 handshake + APP_DATA round-trips back-to-back on the same
/// listener. Validates that no session state (master secret, key block,
/// transcript) leaks between consecutive independent handshakes.
#[tokio::test]
#[ignore = "requires the `gmssl` binary on PATH; run with `-- --ignored`"]
async fn gmssl_tlcp_multiple_sequential_sessions() {
    if !support::cert_setup::gmssl_present() {
        eprintln!("gmssl not on PATH; skipping");
        return;
    }

    let tmp = std::env::temp_dir().join(format!("gm-tlcp-multi-{}-{}", std::process::id(), "F"));
    let _ = std::fs::remove_dir_all(&tmp);
    let certs = support::cert_setup::generate_test_certs(&tmp).expect("generate test certs");

    let port = pick_free_port();
    let server = spawn_gmssl_tlcp_server(&certs, port, TLCP_CIPHER_SUITES)
        .await
        .expect("spawn gmssl");
    wait_for_port(port).await.expect("server listening");

    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    for i in 0..3 {
        // Each iteration builds a fresh connector with the full
        // client-cert chain (required by GmSSL 2026-06+ master for
        // all ECDHE_*_SM4_* suites), so the new session ID and
        // ephemeral keys don't collide with any prior session's
        // cached state.
        let mut connector = build_gmssl_compatible_connector(&certs, Some(TLCP_CIPHER_SUITES));
        let tcp = TcpStream::connect(addr).await.expect("TCP connect");
        let mut client = connector.connect_with_certs(tcp).await.expect("handshake");

        // Distinct payload per session — if state leaked, the same key
        // would produce wrong ciphertext or a wrong echo.
        let payload = format!("session-{}-payload", i).into_bytes();
        client
            .write_application_data(&payload)
            .await
            .expect("write");
        let echoed = client.read_application_data().await.expect("read");
        assert_eq!(echoed, payload, "session {} payload round-trip mismatch", i);
        client.close().await.expect("close");
    }
    drop(server);

    eprintln!("multiple-sequential-sessions (3× on same port): PASS");
}
